#!/usr/bin/env python3
"""
Configuration of running routers: show running-config, push config, and save
the running config back into the node's startup-config file.

Why "save to startup" matters: containerlab can only apply topology changes to
vrnetlab routers by redeploying, and a redeploy boots every VM from its
startup-config. Saving the running config first is what makes a redeploy keep
whatever was configured on the box.

Supported kinds are the ones the dashboard has templates for. The vrnetlab
ones run a VM inside the container, reached over SSH on its management
address; FRR and SR Linux are native containers, driven with docker exec:

    cisco_c8000v, cisco_csr1000v   netmiko cisco_xe
    cisco_xrd_vrouter              netmiko cisco_xr
    cisco_n9kv                     netmiko cisco_nxos
    linux + an FRR image           docker exec vtysh    (frr.conf is bind-mounted)
    nokia_srlinux                  docker exec sr_cli   (startup is a .cli file)

The client names a lab id and a node name; the container, address, platform
and credentials are all resolved here from the server's own lab index and the
topology file. Credentials never leave the server.

Startup-config cleaning (what the vrnetlab launchers accept at first boot):

  IOS-XE  the launcher writes its bootstrap (hostname, clab user, clab-mgmt VRF,
          Gi1, netconf) and appends our file into a config ISO that IOS applies
          line by line, AFTER the bootstrap. From `show running-config` we drop
          the banner lines (Building / Current configuration, Last configuration
          change), what the bootstrap owns (vrf definition clab-mgmt, interface
          GigabitEthernet1, the clab-mgmt default routes, the clab username -
          otherwise stale management addressing or an old password would win),
          the crypto pki trustpoint + certificate-chain blocks (self-signed and
          SLA certs are regenerated by the box; their hex dumps do not re-apply),
          the license udi/boot lines and the netconf/restconf lines the bootstrap
          already sets ("netconf detailed-error" is rejected when re-applied). Every interface that is not shut gets
          an explicit "no shutdown" (running-config omits it; data ports boot
          shut).
  IOS-XR  the launcher prepends its bootstrap and loads the whole file as XR
          first-boot config (no commit needed). We drop the timestamp line and
          the "!! ..." header, the MgmtEth0/RP0/CPU0/0 block and the clab
          username block (the bootstrap owns both), add "no shutdown" to every
          interface that is not shut, and make sure the file ends with "end".
"""

import io
import os
import re
import time

import yaml

import editor
import sysbin

DOCKER = sysbin.find("docker")

SUPPORTED = {
    "cisco_c8000v": "cisco_xe",
    "cisco_csr1000v": "cisco_xe",
    "cisco_xrd_vrouter": "cisco_xr",
    "cisco_n9kv": "cisco_nxos",
    "nokia_srlinux": "srl",
}
PLATFORM_NAMES = {"cisco_xe": "IOS-XE", "cisco_xr": "IOS-XR", "cisco_nxos": "NX-OS",
                  "frr": "FRR", "srl": "SR Linux"}
# Native containers are driven with docker exec, not SSH: FRR through vtysh,
# SR Linux through sr_cli. Everything else here is a VM reached over SSH.
EXEC_PLATFORMS = ("frr", "srl")
FRR_IMAGE_RE = re.compile(r"(^|/)frr(outing)?(/frr)?(:|$)|frrouting/")


def platform_of(kind, image):
    """devcfg platform for a node, or None. FRR is a linux kind with an FRR image."""
    if kind == "linux" and FRR_IMAGE_RE.search(str(image or "")):
        return "frr"
    return SUPPORTED.get(kind)
DEFAULT_USER = "clab"
DEFAULT_PASS = "clab@123"
# containerlab's documented default logins for kinds that do not take theirs
# from USERNAME / PASSWORD (native container NOSes). vrnetlab kinds are read
# from the container's --username/--password instead, see credentials().
KIND_LOGINS = {
    "nokia_srlinux": ("admin", "NokiaSrl1!"), "srl": ("admin", "NokiaSrl1!"),
    "arista_ceos": ("admin", "admin"), "ceos": ("admin", "admin"),
    "juniper_crpd": ("root", "clab123"), "crpd": ("root", "clab123"),
    "cisco_c8000v": ("admin", "admin"), "cisco_csr1000v": ("admin", "admin"),
    "cisco_cat9kv": ("admin", "admin"), "cisco_n9kv": ("admin", "admin"),
    "cisco_iol": ("admin", "admin"), "cisco_ftdv": ("admin", "Admin@123"),
    "arista_veos": ("admin", "admin"), "nokia_sros": ("admin", "admin"),
    "juniper_vmx": ("admin", "admin@123"), "juniper_vjunosrouter": ("admin", "admin@123"),
    "juniper_vjunosswitch": ("admin", "admin@123"), "juniper_vjunosevolved": ("admin", "admin@123"),
    "juniper_vsrx": ("admin", "admin@123"), "juniper_vqfx": ("admin", "admin@123"),
    "sonic-vs": ("admin", "YourPaSsWoRd"), "cumulus_cvx": ("root", "root"),
}
MAX_CONFIG_BYTES = 256 * 1024
NODE_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]{0,80}$")

XE_ERR = re.compile(r"^\s*% ?(Invalid|Incomplete|Ambiguous|Unknown|Unrecognized|Bad|Error|"
                    r"[A-Z][^\n]*(not|failed|error))", re.I | re.M)
NXOS_ERR = re.compile(r"^\s*(% ?(Invalid|Incomplete|Ambiguous)[^\n]*|ERROR:[^\n]*|"
                      r"% ?[^\n]*(not|failed|error)[^\n]*)", re.I | re.M)
XR_ERR = re.compile(r"^\s*% ?(Invalid|Incomplete|Ambiguous|Unknown|Failed)", re.I | re.M)


class DevError(Exception):
    def __init__(self, msg, status=400):
        super().__init__(msg)
        self.status = status


# --------------------------------------------------------------------------
# resolution
# --------------------------------------------------------------------------

def _topo_doc(lab):
    with open(lab["path"]) as fh:
        return yaml.safe_load(fh) or {}


def _node_cfg(doc, node):
    topo = doc.get("topology") or {}
    nodes = topo.get("nodes") or {}
    ncfg = nodes.get(node) if isinstance(nodes, dict) else None
    ncfg = ncfg if isinstance(ncfg, dict) else {}
    defaults = topo.get("defaults") if isinstance(topo.get("defaults"), dict) else {}
    kind = ncfg.get("kind") or defaults.get("kind")
    kinds = topo.get("kinds") if isinstance(topo.get("kinds"), dict) else {}
    kcfg = kinds.get(kind) if isinstance(kinds.get(kind), dict) else {}
    return ncfg, kcfg, defaults, kind


def credentials(lab, node):
    """USERNAME / PASSWORD from the topology (node > kind > defaults), as term.py does."""
    user, pw = DEFAULT_USER, DEFAULT_PASS
    try:
        doc = _topo_doc(lab)
    except Exception:                                   # noqa: BLE001
        return user, pw
    ncfg, kcfg, defaults, kind = _node_cfg(doc, node)
    user, pw = KIND_LOGINS.get(kind, (user, pw))
    env = {}
    for src in (defaults.get("env"), kcfg.get("env"), ncfg.get("env")):
        if isinstance(src, dict):
            env.update(src)
    # native container NOSes ignore USERNAME / PASSWORD - their login is fixed
    native = kind in ("nokia_srlinux", "srl", "arista_ceos", "ceos", "juniper_crpd", "crpd")
    if env.get("USERNAME") and not native:
        user = str(env["USERNAME"])
    if env.get("PASSWORD") and not native:
        pw = str(env["PASSWORD"])
    # What the router was really given wins: containerlab hands vrnetlab its
    # credentials as --username/--password, and for some kinds (n9kv: always
    # admin/admin) it ignores the topology's USERNAME/PASSWORD.
    args = _container_args(lab, node)
    if args.get("username") and args.get("password"):
        user, pw = args["username"], args["password"]
    return user, pw


def _container_args(lab, node):
    import json as _json
    import subprocess
    name = next((c.get("name") for c in lab.get("containers") or [] if c.get("short") == node), None)
    if not name:
        return {}
    try:
        out = subprocess.run([DOCKER, "inspect", "-f", "{{json .Config.Cmd}}", name],
                             capture_output=True, text=True, timeout=15).stdout
        cmd = _json.loads(out or "null") or []
    except Exception:                                   # noqa: BLE001
        return {}
    res = {}
    for i, a in enumerate(cmd[:-1]):
        if a in ("--username", "--password"):
            res[a[2:]] = cmd[i + 1]
    return res


def resolve(lab_index, lab_id, node):
    """(lab, node entry, container, platform) for a running, supported node."""
    lab = lab_index.get(lab_id)
    if lab is None:
        raise DevError("unknown lab id", 404)
    if not isinstance(node, str) or not NODE_RE.match(node):
        raise DevError("bad node name")
    nent = next((n for n in lab.get("nodes") or [] if n.get("name") == node), None)
    if nent is None:
        raise DevError("%s is not a node of %s" % (node, lab.get("name")), 404)
    platform = platform_of(nent.get("kind"), nent.get("image"))
    if not platform:
        raise DevError("%s is %s - device configuration is available for IOS-XE "
                       "(c8000v, csr1000v), IOS-XR (XRd), NX-OS (n9kv), FRR and SR Linux "
                       "nodes" % (node, nent.get("kind")))
    c = next((c for c in lab.get("containers") or [] if c.get("short") == node), None)
    if not c or c.get("state") != "running" or not (c.get("ipv4") or platform in EXEC_PLATFORMS):
        raise DevError("%s is not running - start the lab first" % node, 409)
    return lab, nent, c, platform


# vtysh prints these on every call when /etc/frr/vtysh.conf does not exist
_VTYSH_NOISE = re.compile(r"^(% Can't open configuration file /etc/frr/vtysh\.conf.*|"
                          r"Configuration file\[/etc/frr/frr\.conf\] processing failure: 11)$")


class ExecConn:
    """The two calls devcfg makes on a netmiko connection, over docker exec."""

    def __init__(self, container, platform):
        self.container, self.platform = container, platform

    def exec(self, argv, stdin=None, timeout=60):
        import subprocess
        try:
            p = subprocess.run([DOCKER, "exec", "-i", self.container] + argv,
                               input=stdin, capture_output=True, text=True, timeout=timeout)
        except Exception as exc:                        # noqa: BLE001
            raise DevError("%s: %s" % (self.container, exc), 502)
        out = "\n".join(l for l in (p.stdout + p.stderr).splitlines() if not _VTYSH_NOISE.match(l))
        return p.returncode, out

    def send_command(self, cmd, read_timeout=60, **_):
        if self.platform == "frr":
            return self.exec(["vtysh", "-c", cmd], timeout=read_timeout)[1]
        return self.exec(["sr_cli", "-d", cmd], timeout=read_timeout)[1]

    def disconnect(self):
        pass


def _connect(lab, node, container, platform, timeout=60):
    if platform in EXEC_PLATFORMS:
        return ExecConn(container["name"], platform)
    from netmiko import ConnectHandler
    user, pw = credentials(lab, node)
    try:
        return ConnectHandler(
            device_type=platform, host=container["ipv4"], username=user, password=pw,
            conn_timeout=20, auth_timeout=30, banner_timeout=30, read_timeout_override=None,
            fast_cli=False, global_delay_factor=1, session_timeout=timeout,
        )
    except Exception as exc:                            # noqa: BLE001
        raise DevError("could not log in to %s (%s): %s - it may still be booting"
                       % (node, container["ipv4"], str(exc).splitlines()[0][:200]), 502)


# --------------------------------------------------------------------------
# running-config and cleaning
# --------------------------------------------------------------------------

def _fetch_running(conn):
    if isinstance(conn, ExecConn) and conn.platform == "srl":
        return conn.send_command("info flat", read_timeout=90)
    return conn.send_command("show running-config", read_timeout=90)


# Top-level IOS-XE blocks the saved startup-config must not carry, each with
# its indented children. The first group is what vrnetlab's bootstrap owns
# (management VRF + GigabitEthernet1 - saving them would pin the old
# management addressing, because the startup file is applied after the
# bootstrap); the crypto pki blocks are the self-signed and SLA certificates,
# which the box regenerates and whose hex dumps do not re-apply.
XE_DROP_BLOCKS = [
    r"^interface GigabitEthernet ?1$",
    r"^vrf definition clab-mgmt$",
    r"^crypto pki (trustpoint|certificate chain) ",
]
XE_DROP_LINES = [
    r"^Building configuration",
    r"^Current configuration",
    r"^! Last configuration change",
    r"^! NVRAM config last updated",
    r"^license (udi|boot level|smart)",
    r"^ip route vrf clab-mgmt ",
    r"^ipv6 route vrf clab-mgmt ",
    # netconf/restconf are switched on by the bootstrap; re-applying
    # "netconf detailed-error" from the ISO is rejected (CVAC PRC_INVALID)
    r"^netconf (detailed-error|max-sessions)",
    r"^netconf-yang$",
    r"^restconf$",
    # a platform default IOS-XE writes itself and rejects when re-applied
    r"^platform sslvpn use-pd",
]


def _drop(text, blocks, lines_re):
    out, skipping = [], False
    for line in text.replace("\r", "").split("\n"):
        if skipping:
            if line.startswith((" ", "\t")) or line.strip() == "quit":
                continue
            skipping = False
        if any(re.match(p, line) for p in blocks):
            skipping = True
            continue
        if any(re.match(p, line) for p in lines_re):
            continue
        out.append(line)
    # collapse the runs of top-level "!" that removed blocks leave behind;
    # indented "!" lines are left alone - in XR sub-modes they close a block
    res = []
    for line in out:
        if line.rstrip() == "!" and res and res[-1].rstrip() == "!":
            continue
        res.append(line)
    while res and res[0].strip() in ("", "!"):  # noqa: E501 (leading separators)
        res.pop(0)
    txt = "\n".join(res).rstrip() + "\n"
    if not txt.rstrip().endswith("end"):
        txt += "end\n"
    return txt


def _explicit_no_shut(text):
    """`show running-config` omits "no shutdown" on an interface that is up
    (it is the displayed default), but these routers boot their data
    interfaces shut. Add it to every interface block that is not shut, so a
    saved config brings the links back up after a redeploy."""
    out, block = [], None
    lines = text.split("\n")

    def close():
        if block is not None and not block["shut"]:
            out.insert(block["end"], " no shutdown")

    for line in lines:
        if line.startswith("interface "):
            close()
            out.append(line)
            block = {"end": len(out), "shut": False}
            continue
        if block is not None:
            if line.startswith(" "):
                if line.strip() == "shutdown":
                    block["shut"] = True
                out.append(line)
                block["end"] = len(out)
                continue
            close()
            block = None
        out.append(line)
    close()
    return "\n".join(out)


def clean_xe(text, user=DEFAULT_USER):
    """IOS-XE running-config -> startup-config for the vrnetlab c8000v launcher."""
    return _explicit_no_shut(_drop(text, XE_DROP_BLOCKS,
                                   XE_DROP_LINES + [r"^username %s " % re.escape(user)]))


# IOS-XR: the launcher's first-boot bootstrap owns the clab user and MgmtEth.
XR_DROP_BLOCKS = [r"^interface MgmtEth0/RP0/CPU0/0$"]
XR_DROP_LINES = [
    r"^!! ",
    r"^[A-Z][a-z]{2} [A-Z][a-z]{2} +\d+ \d\d:\d\d:\d\d",   # "Sat Sep 19 16:54:09.449 UTC"
    r"^Building configuration",
]


def clean_xr(text, user=DEFAULT_USER):
    """IOS-XR running-config -> first-boot config for the vrnetlab XRd launcher."""
    return _explicit_no_shut(_drop(text, XR_DROP_BLOCKS + [r"^username %s$" % re.escape(user)],
                                   XR_DROP_LINES))


# NX-OS: the n9kv launcher's bootstrap owns hostname-adjacent housekeeping, the
# users, VRF management and mgmt0; it feeds our file line by line in config mode
# (so no "end"). Running-config already shows "no shutdown" explicitly.
NXOS_DROP_BLOCKS = [r"^vdc ", r"^vrf context management$", r"^interface mgmt0$"]
NXOS_DROP_LINES = [
    r"^!Command:", r"^!Running configuration", r"^!Time:", r"^!NVRAM config",
    r"^version ", r"^snmp-server user ", r"^boot nxos ",
    r"^ssh key ", r"^ip route 0\.0\.0\.0/0 .* vrf management",
]


def clean_nxos(text, user=DEFAULT_USER):
    # only the launcher's own login user is dropped (it recreates it); other
    # users - e.g. the lab's clab user - are kept, hashed passwords re-apply
    out = _drop(text, NXOS_DROP_BLOCKS,
                NXOS_DROP_LINES + [r"^username (%s|admin) " % re.escape(user)])
    lines = out.rstrip("\n").split("\n")
    if lines and lines[-1].strip() == "end":
        lines.pop()
    return "\n".join(l for l in lines) .rstrip() + "\n"


def clean_frr(text):
    """vtysh `show running-config` -> frr.conf (no banner, no trailing end)."""
    lines = [l for l in text.replace("\r", "").split("\n")
             if not re.match(r"^(Building configuration|Current configuration)", l)]
    while lines and lines[0].strip() in ("", "!"):
        lines.pop(0)
    while lines and lines[-1].strip() in ("", "end"):
        lines.pop()
    return "\n".join(lines).rstrip() + "\n"


# What containerlab's SR Linux bootstrap owns (management, TLS, gNMI/JSON-RPC,
# AAA users, the factory CPM filters): saving it would pin old certificates and
# keys and fight the next deploy. Everything else is kept.
SRL_DROP = re.compile(r"^set / (system (tls|grpc-server|json-rpc-server|aaa|ssh-server|"
                      r"management|snmp|netconf-server|gnmi-server|banner|dns|lldp|"
                      r"logging|information|name|dns-instance|control-plane-traffic|ndk-server)|"
                      r"network-instance mgmt|interface mgmt0|acl|"
                      r"tools|platform|bfd$)(\s|$)")


def clean_srl(text):
    """`info flat` -> a .cli startup file clab applies after boot."""
    out = [l for l in text.replace("\r", "").split("\n")
           if l.startswith("set / ") and not SRL_DROP.match(l)
           and not re.match(r"^set /\s+!", l)]          # "!!! ..." annotations
    return "\n".join(out) + "\n"


def _clean(platform, raw, lab, node):
    if platform == "frr":
        return clean_frr(raw)
    if platform == "srl":
        return clean_srl(raw)
    user, _ = credentials(lab, node)
    if platform == "cisco_nxos":
        return clean_nxos(raw, user)
    return clean_xe(raw, user) if platform == "cisco_xe" else clean_xr(raw, user)


def running_config(lab_index, lab_id, node):
    lab, nent, c, platform = resolve(lab_index, lab_id, node)
    conn = _connect(lab, node, c, platform)
    try:
        raw = _fetch_running(conn)
    finally:
        conn.disconnect()
    text = _clean(platform, raw, lab, node)
    return {"node": node, "platform": PLATFORM_NAMES[platform], "text": text}


# --------------------------------------------------------------------------
# push
# --------------------------------------------------------------------------

def _config_lines(config):
    if not isinstance(config, str) or not config.strip():
        raise DevError("no configuration to push")
    if len(config.encode()) > MAX_CONFIG_BYTES:
        raise DevError("configuration too large (limit 256 KB)")
    lines = []
    for line in config.replace("\r", "").split("\n"):
        s = line.rstrip()
        if not s.strip():
            continue
        # these are handled here; letting the user send them would leave the
        # session in the wrong mode
        if s.strip().lower() in ("configure terminal", "conf t", "configure", "end", "commit",
                                 "exit config", "abort", "commit now", "enter candidate",
                                 "enter candidate private"):
            continue
        lines.append(s)
    if not lines:
        raise DevError("nothing left to push after removing configure/end/commit")
    return lines


FRR_ERR = re.compile(r"^line \d+: %.*$", re.M)


def push_frr(conn, lines):
    """vtysh -f applies a config file line by line; a bad line is reported per
    daemon as "line N: % ..." and the others are applied."""
    rc, out = conn.exec(["sh", "-c", "cat > /tmp/clabd-push.conf && vtysh -f /tmp/clabd-push.conf; "
                         "rc=$?; rm -f /tmp/clabd-push.conf; exit $rc"],
                        stdin="\n".join(lines) + "\n", timeout=120)
    errors = sorted(set(m.group(0).strip() for m in FRR_ERR.finditer(out)))
    if rc != 0 and not errors:
        errors = [l for l in out.splitlines() if "failure" in l][:5] or ["vtysh exited with %d" % rc]
    return out, errors


def push_srl(conn, lines):
    """SR Linux: the lines go into a private candidate that is committed only if
    every line parsed - a bad line aborts the whole change."""
    bad = [l for l in lines if not re.match(r"^\s*(set|delete) ", l)]
    if bad:
        return "", ["SR Linux takes flat `set / ...` / `delete / ...` lines here; not: %s" % bad[0][:120]]
    rc, out = conn.exec(["sr_cli", "-ed", "--post", "commit now"], stdin="\n".join(lines) + "\n",
                        timeout=120)
    errors = [l.strip() for l in out.splitlines() if re.search(r"(Parsing error|Error|error:)", l)]
    if rc != 0 and not errors:
        errors = ["sr_cli exited with %d" % rc]
    if errors:
        out += "\n--- rejected: nothing was committed ---\n"
    return out, errors


def push_nxos(conn, lines):
    """NX-OS also applies line by line; errors are "% Invalid command" / "ERROR:"."""
    out = conn.send_config_set(lines, read_timeout=120, cmd_verify=True)
    errors = [m.group(0).strip() for m in NXOS_ERR.finditer(out)]
    return out, errors


def push_xe(conn, lines):
    """IOS-XE applies line by line - there is no transaction to roll back. With
    cmd_verify on, netmiko waits for each echo, so the "% Invalid input"
    that IOS prints a moment later lands in the output."""
    out = conn.send_config_set(lines, read_timeout=120, cmd_verify=True)
    errors = [m.group(0).strip() for m in XE_ERR.finditer(out)]
    return out, errors


_XR_INCONSISTENT = "inconsistent with persistent configuration"
_XR_COMMIT_FAIL = re.compile(r"Failed to commit|% ?Failed|commit.*(rejected|failed)|"
                             + _XR_INCONSISTENT, re.I)


def _xr_pending(conn):
    """Uncommitted lines in the current XR config session, if any."""
    show = conn.send_command_timing("show configuration", read_timeout=60)
    body = [l for l in show.splitlines()
            if l.strip() and not l.startswith(("!!", "Building")) and l.strip() not in ("end", "!")
            and not re.match(r"^[A-Z][a-z]{2} [A-Z][a-z]{2} +\d+ ", l) and "#" not in l]
    return body


def _xr_abort(conn):
    return conn.send_command_timing("abort", read_timeout=30)


def push_xr(conn, lines):
    """Enter config, apply, commit - or abort, so nothing is ever half applied.

    A freshly booted XRd refuses every commit until `clear configuration
    inconsistency` has been run; we detect that on entering config mode, run
    it, and say so in the output."""
    out = conn.config_mode()
    if _XR_INCONSISTENT in out:
        out += "\n" + _xr_abort(conn)
        out += "\n--- XR reports running vs persistent configuration inconsistent " \
               "(normal after first boot): running 'clear configuration inconsistency' ---\n"
        out += conn.send_command_timing("clear configuration inconsistency", read_timeout=180,
                                        last_read=4)
        out += "\n" + conn.config_mode()
    out += conn.send_config_set(lines, enter_config_mode=False, exit_config_mode=False,
                                read_timeout=120, cmd_verify=True)
    errors = [m.group(0).strip() for m in XR_ERR.finditer(out)]
    if errors:
        out += "\n" + _xr_abort(conn)
        out += "\n--- rejected while typing: nothing was committed (session aborted) ---\n"
        return out, errors
    commit = conn.send_command_timing("commit", read_timeout=150, last_read=3)
    out += "\n" + commit
    pending = [] if _XR_COMMIT_FAIL.search(commit) else _xr_pending(conn)
    if _XR_COMMIT_FAIL.search(commit) or pending:
        failed = conn.send_command_timing("show configuration failed", read_timeout=60)
        out += "\n" + failed + "\n" + _xr_abort(conn)
        out += "\n--- commit failed: nothing was applied (session aborted) ---\n"
        # the useful part: "!!% <reason>" lines under each rejected command
        reasons = [l.strip().lstrip("!%").strip() for l in failed.splitlines()
                   if l.strip().startswith("!!%")]
        errors = ["commit failed"] + (reasons or [l.strip() for l in commit.splitlines()
                                                 if "Failed to commit" in l])[:20]
        return out, errors
    end = conn.send_command_timing("end", read_timeout=30)
    out += "\n" + end
    if "Uncommitted changes" in end:        # belt and braces: never leave a prompt open
        out += conn.send_command_timing("no", read_timeout=30)
        return out, ["changes were left uncommitted - discarded"]
    return out, []


def push_config(lab_index, lab_id, node, config, save_startup_after=False, audit=None):
    lab, nent, c, platform = resolve(lab_index, lab_id, node)
    lines = _config_lines(config)
    conn = _connect(lab, node, c, platform, timeout=150)
    t0 = time.time()
    try:
        if platform == "cisco_xe":
            out, errors = push_xe(conn, lines)
        elif platform == "frr":
            out, errors = push_frr(conn, lines)
        elif platform == "srl":
            out, errors = push_srl(conn, lines)
        elif platform == "cisco_nxos":
            out, errors = push_nxos(conn, lines)
        else:
            out, errors = push_xr(conn, lines)
    finally:
        try:
            conn.disconnect()
        except Exception:                               # noqa: BLE001
            pass
    ok = not errors
    res = {"node": node, "ok": ok, "errors": errors, "output": out.replace("\r", ""),
           "lines": len(lines), "seconds": round(time.time() - t0, 1),
           "platform": PLATFORM_NAMES[platform]}
    if platform in ("cisco_xe", "cisco_nxos", "frr") and errors:
        res["note"] = ("%s applies configuration line by line: the lines without an "
                       "error were applied." % PLATFORM_NAMES[platform])
    if audit:
        audit("DEVICE-CONFIG lab=%s node=%s lines=%d ok=%s"
              % (lab.get("name"), node, len(lines), ok))
    if save_startup_after and (ok or platform in ("cisco_xe", "cisco_nxos", "frr")):
        res["saved"] = save_startup(lab, node, audit=audit)
    return res


# --------------------------------------------------------------------------
# save running -> startup
# --------------------------------------------------------------------------

def _pick_yaml(text):
    """A ruamel round-trip YAML whose indentation reproduces this file best."""
    from ruamel.yaml import YAML
    best, best_score = None, None
    for mapping, seq, offset in ((2, 4, 2), (2, 2, 0), (4, 4, 2), (2, 4, 0), (4, 6, 4)):
        y = YAML()
        y.preserve_quotes = True
        y.width = 4096
        y.indent(mapping=mapping, sequence=seq, offset=offset)
        try:
            doc = y.load(text)
            buf = io.StringIO()
            y.dump(doc, buf)
        except Exception:                               # noqa: BLE001
            continue
        a, b = text.splitlines(), buf.getvalue().splitlines()
        score = sum(1 for x, z in zip(a, b) if x != z) + abs(len(a) - len(b))
        if best_score is None or score < best_score:
            best, best_score = y, score
        if score == 0:
            break
    if best is None:
        raise DevError("the topology file could not be parsed for a round-trip edit")
    return best


def _set_node_startup(lab, node, rel):
    """Add startup-config: rel to the node in the topology, comments preserved."""
    with open(lab["path"]) as fh:
        text = fh.read()
    y = _pick_yaml(text)
    doc = y.load(text)
    nodes = doc["topology"]["nodes"]
    if nodes.get(node) is None:
        nodes[node] = {}
    nodes[node]["startup-config"] = rel
    buf = io.StringIO()
    y.dump(doc, buf)
    new = buf.getvalue()
    return editor.write_file(lab, os.path.basename(lab["path"]), new, editor.sha(text))


def _add_node_bind(lab, node, rel, target):
    """Add a `rel:target` bind to the node in the topology, comments preserved."""
    with open(lab["path"]) as fh:
        text = fh.read()
    y = _pick_yaml(text)
    doc = y.load(text)
    nodes = doc["topology"]["nodes"]
    if nodes.get(node) is None:
        nodes[node] = {}
    binds = nodes[node].get("binds")
    if binds is None:
        nodes[node]["binds"] = binds = []
    binds.append("%s:%s" % (rel, target))
    buf = io.StringIO()
    y.dump(doc, buf)
    return editor.write_file(lab, os.path.basename(lab["path"]), buf.getvalue(), editor.sha(text))


def _frr_conf_rel(lab, node):
    """(path of the file bind-mounted as /etc/frr/frr.conf, whether to add the bind)."""
    doc = _topo_doc(lab)
    ncfg, kcfg, defaults, _ = _node_cfg(doc, node)
    base = os.path.dirname(lab["path"])
    for src in (ncfg, kcfg, defaults):
        for b in src.get("binds") or []:
            host, _, rest = str(b).partition(":")
            if rest.split(":")[0] == "/etc/frr/frr.conf" and editor._inside(base, host):
                return os.path.normpath(host), False
    return os.path.join("configs", "%s.frr.conf" % node), True


def _startup_rel(lab, node, platform=None):
    """(relative path to write, whether the topology must be pointed at it)."""
    if platform == "frr":
        return _frr_conf_rel(lab, node)
    doc = _topo_doc(lab)
    ncfg, kcfg, defaults, _ = _node_cfg(doc, node)
    sc = ncfg.get("startup-config")
    base = os.path.dirname(lab["path"])
    if isinstance(sc, str) and "\n" not in sc and not sc.startswith("/") \
            and "{{" not in sc and "__clab" not in sc:
        full = os.path.normpath(os.path.join(base, sc))
        if full.startswith(os.path.realpath(base) + os.sep) or full.startswith(base + os.sep):
            return os.path.normpath(sc), False
    # no per-node file (or inline / templated / outside the lab dir): give the
    # node its own file
    return os.path.join("configs", "%s.%s" % (node, "cli" if platform == "srl" else "cfg")), True


def save_startup(lab, node, audit=None):
    """Write the node's cleaned running-config into its startup-config file.

    lab is a lab dict from the collector (needs path, name, nodes, containers).
    Returns {"node", "path", "created", "topology_updated", "saved_version", "bytes"}.
    """
    _, nent, c, platform = resolve({lab["id"]: lab}, lab["id"], node)
    conn = _connect(lab, node, c, platform)
    try:
        raw = _fetch_running(conn)
    finally:
        conn.disconnect()
    text = _clean(platform, raw, lab, node)
    if len(text.splitlines()) < 3 or ("hostname" not in text and platform != "srl"):
        raise DevError("the running-config from %s looks truncated - not saved" % node, 502)

    rel, repoint = _startup_rel(lab, node, platform)
    full = os.path.join(os.path.dirname(lab["path"]), rel)
    exists = os.path.isfile(full)
    res = {"node": node, "path": rel, "created": not exists, "topology_updated": False,
           "bytes": len(text)}
    # file first, so the topology never points at something missing
    w = editor.write_file(lab, rel, text, None, create=not exists)
    if repoint and platform == "frr":
        _add_node_bind(lab, node, rel, "/etc/frr/frr.conf")
        res["topology_updated"] = True
        res["note"] = "the topology now bind-mounts %s; it takes effect at the next deploy" % rel
    elif repoint:
        _set_node_startup(lab, node, rel)
        res["topology_updated"] = True
    res["saved_version"] = (w or {}).get("saved_version")
    if audit:
        audit("DEVICE-SAVE lab=%s node=%s file=%s bytes=%d previous-kept=%s"
              % (lab.get("name"), node, rel, len(text), res["saved_version"]))
    return res


# --------------------------------------------------------------------------
# HTTP glue (server.py calls these)
# --------------------------------------------------------------------------

def _err(exc):
    status = getattr(exc, "status", 400)
    return status, {"error": str(exc)}


def handle_get(path, q, lab_index):
    """GET routes. Returns (status, body), or None when the path is not ours."""
    if path != "/api/device/running":
        return None
    try:
        return 200, running_config(lab_index, q.get("lab", ""), q.get("node", ""))
    except (DevError, editor.EditError) as exc:
        return _err(exc)


def _post_config(payload, lab_index, audit):
    try:
        return 200, push_config(lab_index, payload.get("lab_id"), payload.get("node"),
                                payload.get("config"), bool(payload.get("save_startup")),
                                audit=audit)
    except (DevError, editor.EditError) as exc:
        return _err(exc)


def _post_save(payload, lab_index, audit):
    try:
        lab = lab_index.get(payload.get("lab_id"))
        if lab is None:
            raise DevError("unknown lab id", 404)
        return 200, save_startup(lab, payload.get("node"), audit=audit)
    except (DevError, editor.EditError) as exc:
        return _err(exc)


POST_ROUTES = {
    "/api/device/config": _post_config,
    "/api/device/save-startup": _post_save,
}
